### ISSUE TITLE
App doesn't close after closing window

### ISSUE THREAD

**Issue by PeGa** [danielchatfield/trello-desktop#11]
In Gentoo GNU/Linux, running the app from a terminal reveals that after closing the app window the process is still running.

**System properties**
- Kernel: pf-sources v4.4_p8
  `Linux 4.4.0-pf8 #3 SMP PREEMPT Wed Sep 14 03:54:56 ART 2016 x86_64 AuthenticAMD GNU/Linux`
- Desktop environment: KDE5 with plasma-desktop.
  `kde-apps/kdebase-runtime-meta (15.12.3(5)@02/05/16`

**Edit**

Pressing Alt key in the keyboard raises a hidden application menu. The `Quit` option under the `File` menu does close the application.

**Comment by PeyTy** [comment]
Same on stock Ubuntu 16.04, using `killall -9 Trello` for now :smile:

**Comment by fennecdjay** [comment]
same on archlinux, dwm.

**Comment by kenrick95** [comment]
This is also the case in Windows: the processes are still running even after closing the application's window.

**Comment by yurivecchi** [comment]
@danielchatfield can we make a release?

**Comment by fennecdjay** [comment]
That works for me. Thank you.

**Comment by yurivecchi** [comment]
fixed guys!!!
