### ISSUE TITLE
Looses last window size on restart.

### ISSUE THREAD

**Issue by ekundayo-ab** [danielchatfield/trello-desktop#23]
Trello unofficial app for windows looses its last windows size when its restarted.

How do i fix this?

Thanks

![trello](https://cloud.githubusercontent.com/assets/20375577/25847110/aaca94a4-34ac-11e7-8c6b-cd638dbb1a2f.jpg)

**Comment by panjandrum** [comment]
Same on Ubuntu 16.04. The window is very small after restart.

**Comment by GreenRobot777** [comment]
#14

**Comment by yurivecchi** [comment]
fixed guys!!!
