### ISSUE TITLE
Add trellius calendar for trello

### ISSUE THREAD

**Issue by Melcreatie** [danielchatfield/trello-desktop#24]
Trellius calendar is only accessible with trello online.
When I  activate the power ups in the desktop app and authorize trellius.
The link open a blanck page.
Is there a possibility to add trellius on trello app desktop?
Thank you!

**Comment by yurivecchi** [comment]
hi @Melcreatie , I think the most correct way is using the powerup: [https://planyway.com/powerup/](https://planyway.com/powerup/)

PS: they changed their name
