### ISSUE TITLE
Need to log-in everytime the app is reopened

### ISSUE THREAD

**Issue by compiaffe** [danielchatfield/trello-desktop#25]
This started about 2 days ago on a Fedora 25 machine.

Whenever I restart trello-desktop, it asks me for my password. 
Even a clean closing of the app and starting it again has this effect.

Thinking this was a permissions problem I checked file permissions in the ~/.config/Trello folder, but nothing obvious there:

    .config % ls Trello -alh
    total 44K
    drwxrwxr-x.  5 rapha rapha 4.0K May 19 11:36 .
    drwxr-xr-x. 73 rapha rapha 4.0K May 19 11:36 ..
    drwx------.  2 rapha rapha 4.0K May 19 11:37 Cache
    -rw-rw-r--.  1 rapha rapha   94 May 19 11:36 config.json
    -rw-r--r--.  1 rapha rapha  10K May 19 11:36 Cookies
    -rw-r--r--.  1 rapha rapha    0 May 19 11:36 Cookies-journal
    drwx------.  2 rapha rapha 4.0K May 19 11:36 GPUCache
    drwx------.  2 rapha rapha 4.0K May 19 11:36 'Local Storage'
    -rw-------.  1 rapha rapha   69 May 19 11:36 Preferences

Removing the folder and restarting the app didn't help either.
Any thoughts?

**Comment by InigoWD** [comment]
Same issue here, on Windows 7

**Comment by jmason86** [comment]
Same issue here, on macOS 10.12.5

**Comment by diegotoral** [comment]
I can confirm this issue on macOS. I think something has changed on Trello, not sure.

**Comment by madonit** [comment]
Same issue here, on Windows 10

While I solve this question so, waiting for the solution of the issue:
Click link Reset it, then click button Go to Your Boards. Enjoy!)

**Comment by CyanBlob** [comment]
I can confirm this issue on Arch.

**Comment by bohegeek** [comment]
I can confirm the issue on macOS 10.11 and Windows 7

**Comment by leifniem** [comment]
I think this is an omnipresent issue. No need to confirm this anymore.

**Comment by yurivecchi** [comment]
Hello everyone, I will be looking into this during the week,

**Comment by GreenRobot777** [comment]
This is fixed in this fork: https://github.com/1000ch/whale

**Comment by yurivecchi** [comment]
I already found the solution, the fix is on the way...

**Comment by yurivecchi** [comment]
fixed guys!!!

**Comment by mvrozanti** [comment]
I'm having this issue on Arch Linux
