### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by maethor** [danielchatfield/trello-desktop#3]
On debian testing, the app was working just fine until today. Now I just have a complete blank page, no error, nothing. I tried to redownload it, to build it from source, to remove cache and config, to run it with another user… but didn't succeed to make it work again. I'm sure I did'nt break anything because I have the exact same electron app with another URL, and it is still working fine.

Am I the only one to have this problem with Trello?

Thanks.

**Comment by danielchatfield** [comment]
Still works for me. What happens if you open the dev tools?

**Comment by maethor** [comment]
This morning it's working fine… I have done nothing more, and I don't have a clue of what may have happen :(

Thanks anyway.
