### ISSUE TITLE
Can't paste text in new card or the comment box

### ISSUE THREAD

**Issue by smehenni** [danielchatfield/trello-desktop#4]
Hi, great work Daniel, slick design.
However, I just realized that I can't paste text anywhere in the desktop app (**_cmd + V_** or **_right click_**). Wondering if I'm crazy or it's a feature you need to work on, ha?

Thanks!

EDIT: [Just found this](https://github.com/electron/electron/issues/2591)

**Comment by danielchatfield** [comment]
@smehenni I've fixed this :)
