### ISSUE TITLE
can't open in the newest ubuntu 

### ISSUE THREAD

**Issue by ghost** [danielchatfield/trello-desktop#50]
Hi, you made a great tool, but in the newest Ubuntu I can't open it, when I opened  by apt-file, it has an exception: invalid URL: No':'url. thanks for watching and keep up your good work! many thanks!

**Comment by ghost** [comment]
when i write `~/app-linux/trello/Trello`
--->  `/home/nguyensang/app-linux/trello/Trello: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory`

**Comment by kevinNejad** [comment]
+1 Ubuntu 18.04

**Comment by cmoro-deusto** [comment]
@nooboyvn @kevinNejad try to install libgconf-2-4:

```
 sudo apt-get install libgconf-2-4
```

**Comment by ghost** [comment]
I got it many thanks!
