### ISSUE TITLE
Cannot find the application icon in Ubuntu 14.04.5

### ISSUE THREAD

**Issue by husnain-ahmad** [danielchatfield/trello-desktop#7]
I have set up trello as per your instructions and have created a trello.desktop file in ~/locale/share/applications/ but I cannot find any icon anywhere. Please tell me what should I do? 
As of now I run the application from terminal.

**Comment by PeyTy** [comment]
@husnain-ahmad Please, close if fixed in https://github.com/danielchatfield/trello-desktop/pull/8

**Comment by husnain-ahmad** [comment]
It's fixed. Thanks. 
Great Job people. :+1:
