### ISSUE TITLE
How to use ses.loadExtension() Chrome for trello-desktop

### ISSUE THREAD

**Issue by peter-dinh** [danielchatfield/trello-desktop#77]
I want trello desktop which load some chrome extension
How to make that?

**Comment by tara-bartlett** [comment]
Hi @peter-dinh, did you figure out how to do it? If so, please share :)

**Comment by peter-dinh** [comment]
OK>

I use `electron == 9.x` and add new line `page.session.loadExtension( path.join(__dirname, 'extensions/XXXXX'))` in `ready` event

You can see at https://www.electronjs.org/docs/api/extensions#loading-extensions
