### ISSUE TITLE
can't open in the newest ubuntu

### ISSUE THREAD

**Issue by crisnsz** [danielchatfield/trello-desktop#82]
Hello, it's a wonderful tool, but in the newest Ubuntu(20.10) I can't open it.
I saw the another threads similar to this problem and some say to install libgconf-2-4, but i had already installed.

**Comment by angsuman** [comment]
The error I am getting on Ubuntu 20.04:
```
./Trello

(Trello:1698227): Pango-ERROR **: 17:48:26.504: Harfbuzz version too old (1.4.2)

Trace/breakpoint trap (core dumped)
```

**Comment by crisnsz** [comment]
> The error I am getting on Ubuntu 20.04:
> 
> ```
> ./Trello
> 
> (Trello:1698227): Pango-ERROR **: 17:48:26.504: Harfbuzz version too old (1.4.2)
> 
> Trace/breakpoint trap (core dumped)
> ```
Hi, I found a solution.
You have to import the dependencies([libpango(Dependencies).zip](https://github.com/danielchatfield/trello-desktop/files/5774561/libpango.Dependencies.zip)) to where you have installed Trello. 
In my case i have installed in "/opt/trello/", i moved them there.
![image](https://user-images.githubusercontent.com/51567822/103745326-e4752980-4fc4-11eb-983b-946464271d2c.png)

**Comment by crisnsz** [comment]
A solution has been found.

**Comment by xyzib** [comment]
This solution worked for me on 20.04!

**Comment by Alexiades** [comment]
Yes, it works for me too in **ubuntu 20.04**. Thanks

**Comment by gqtn** [comment]
@crisnsz, thank you a lot. It worked for me.
