### ISSUE TITLE
Provide application icon

### ISSUE THREAD

**Issue by jendakol** [danielchatfield/trello-desktop#9]
I'm using the application on Ubuntu 16.04 and it works well, but it doesn't show any icon (system shows the default with question mark).

**Comment by PeyTy** [comment]
@jendakol does it works for you? https://github.com/danielchatfield/trello-desktop/pull/8

**Comment by jendakol** [comment]
@PeyTy I don't know how to proceed. I'm using your latest (and only) release 0.1.1.

**Comment by danielchatfield** [comment]
I'll make a new release soon.
