### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by Vini-Pires** [danielchatfield/trello-desktop#90]
I tried to reinstall trello to v0.1.9 on linux mint vannesa by using terminal, but on finish the installation and tried to run he return the "segmentation fault (core dumped)"

## How I reinstalled
- Removed the old trello
```bash
sudo rm -Rf /opt/trello*
sudo rm -Rf /usr/bin/trello
sudo rm -Rf /usr/share/applications/trello.desktop
```
- Get the repo from github
```bash
wget https://github.com/danielchatfield/trello-desktop/releases/download/v0.1.9/Trello-linux-0.1.9.zip -O trello.zip
```
- Created new directory where will be installed
```bash
sudo mkdir /opt/trello
```
- Unziped trello.zip to this new directory
```bash
sudo unzip trello.zip -d /opt/trello/
```
- Created a shortcut to open it on terminal
```bash
sudo ln -sf /opt/trello/Trello /usr/bin/trello
```
- Created a launcher to the program
```bash
echo -e '[Desktop Entry]\n 
Version=1.0\n Name=trello\n 
Exec=/opt/trello/Trello\n 
Icon=/opt/trello/resources/app/static/Icon.png\n 
Type=Application\n 
Categories=Application' | sudo tee /usr/share/applications/trello.desktop
```

But after all this, the program don't run and I don't know how to solve this problem. 
I'm relative new on linux.

**Comment by crisnsz** [comment]
Hi, could you share a picture or the full text from the output of your terminal?

**Comment by Vini-Pires** [comment]
I just gave up and installed from the snap store
